# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bc79b85d131c11c6373c781cf0f9b828ab2e6a43e08b1d0cc49054db7376ea848e8654396671228c87afe19d4a0626d9105b9731709b6d6980204fd24db3a83

test:
  secret_key_base: a60ccf0703cb14d167ca3bf698d30235ad928baa95d90efd0f6e8890939814968ec44c72a0e985ce1af438458299b930170d625813550295904ac6ea9b441bc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
